name: Testing

on:
  # Run for every push event
  push


jobs:
  # Job to run Pylint with failure condition based on score
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install pylint
          
      - name: Run Pylint
        run: pylint --fail-under=7 src/

  # Job to run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
     
      - name: Run Pytest
        run: pytest --cov=./ --cov-report=lcov:coverage/ tests/
